#!groovy

@Library("multi-demo") _

pipeline {
    environment {
        registry = "vermutr/db"
        registryCredential = 'docker-vermut'
    }

    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Clean') {
            steps {
                gradleTask('clean')
            }
        }

        stage('Build') {
            steps {
                gradleTask('assemble')
            }
        }

        stage('Test') {
            steps {
                gradleTask('test')
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    buildDockerImage(registry, 'latest')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    pushDockerImage(registry, 'latest', registryCredential)
                }
            }
        }
    }
}